### ISSUE TITLE
Please add seamonkey support

### ISSUE THREAD

**Issue by Polynomial-C** [zakius/Polly#10]
Hi,

seamonkey suffers from the same issue with GitHub like waterfox-classic.
I've tried to add polly-1.3 to seamonkey-2.53.4 which succeeds but I don't get any icon where I can choose the polyfill method. 

Any chance this could be fixed?

**Comment by zakius** [comment]
By the error I'm seeing it looks that it would be impossible to do as a WebExtension for SeaMonkey due to API limitations/incompatible manifest schemas.

If there is any proper documentation of WebExtensions for SeaMonkey I can take a deeper look at it but can't promise anything

**Comment by hawkeye116477** [comment]
@Polynomial-Maybe try https://github.com/JustOff/github-wc-polyfill.

**Comment by Polynomial-C** [comment]
Yes, that one helps with seamonkey. Thanks!
