### ISSUE TITLE
Auto Update Doesn't Work.

### ISSUE THREAD

**Issue by pjpreilly** [zakius/Polly#14]
Is it designed to work? I have 1.4 & update check shows no updates available.

**Comment by zakius** [comment]
I haven't looked into autouodate without AMO yet so it's not implemented, may be coming in the future

**Comment by pjpreilly** [comment]
**[Bypass Paywalls](url)** has it working if you want to mind meld.....

**Comment by zakius** [comment]
I prepared part of auto publish workflow already, further steps will be generating proper changelog file, publishing version changes with release and creating/updating autoupdate file

I'll do it as an exercise as I don't expect many updates to come though
