### ISSUE TITLE
Polly breaks plaintext

### ISSUE THREAD

**Issue by aeiouaeiouaeiouaeiouaeiouaeiou** [zakius/Polly#15]
Simple text files cannot be displayed if Polly is enabled ([example 1](https://github.com/zakius/Polly/commit/7cbc5a3d3cdbe3221d3675ad5b00622b9552b07e.patch), [example 2](http://policenauts.net/english/Policenauts_Instruction_Sheet_English.txt)).

![2020-12-07_01-48-03](https://user-images.githubusercontent.com/69355938/101295577-84595f00-382f-11eb-9195-7471b8e0c1a7.png)

**Comment by zakius** [comment]
I'll take a look as soon as I have some spare time, honestly I hope it's my mistake, not spec violation that I have to work around, but we'll see

**Comment by zakius** [comment]
version 1.7 should take care of this, but I'll leave this open just in case
