### ISSUE TITLE
Github's merge pull request doesn't work

### ISSUE THREAD

**Issue by Z0nder** [zakius/Polly#18]
Github's merge pull request doesn't work, it's greyed out with "Hang in there while we check the branch’s status" message there forever. (Waterfox Classic)

**Comment by zakius** [comment]
Can you list the precise steps to reproduce the issue?


Which polyfills you have enabled for GitHub, is Request modification method selected (for GitHub and most other cases it should be), does anything appear in the console?

**Comment by zakius** [comment]
![image](https://user-images.githubusercontent.com/2071503/103798941-ae7a8880-504a-11eb-8760-4bf591fc2fc3.png)

reproducing your steps just worked for me with `Webcomponents-sd` and `Webcomponents-ce` enabled

**Comment by Z0nder** [comment]
Yeap, it works.
Look like it doesn't work when  `Webcomponents-Bundle` is enabled too.

**Comment by zakius** [comment]
bundle is meant to let you click once when you need both of them, having these polyfills loaded twice in that case may break
