### ISSUE TITLE
Polly 1.2 breaks text encoding

### ISSUE THREAD

**Issue by hawkeye116477** [zakius/Polly#4]
As in tiitle. For example go to https://www.gry-online.pl/ and see weird characters.

![2020-10-18_19-32](https://user-images.githubusercontent.com/19818572/96375334-c42d8f80-1178-11eb-9643-477932d816df.png)

**Comment by zakius** [comment]
Thanks for the report, next release will have this issue (and many others related to response handling) fixed

**Comment by zakius** [comment]
I still can't get it to properly display pages with non-utf-8 encoding but they won't be modified unless you choose them to. I'll get back to this tomorrow, hopefully I'll manage to override `content-type` header and it will work this way as `TextEncoder` for some reason can only encode to `utf-8`;

**Comment by zakius** [comment]
Fixed in 1.3
