### ISSUE TITLE
UI appears to be randomly placed checkboxes (maybe text is black on black?)

### ISSUE THREAD

**Issue by happysmash27** [zakius/Polly#5]
As can be seen in [this image](https://happysmash27.me/Upload/Screenshots/2020-10-20-143729_1277x995_scrot.png), the UI is not very usable. 

I apologise for sending a link instead of embed (assuming embeds can be done in GitHub); most if not all GitHub Javascript functionality, including the editing tools, is currently broken for me (which, hopefully this addon can fix when I know which invisible checkbox to check).

**Comment by zakius** [comment]
This should be fixed by your PR, will release this soon. Thanks!
