### ISSUE TITLE
How to package into XPI? 

### ISSUE THREAD

**Issue by happysmash27** [zakius/Polly#6]
I would like to try to use a quick CSS fix I made for issue #5, but there is no documentation on how to package this as an XPI. Perhaps some should be added to README.md.

**Comment by happysmash27** [comment]
After creating a directory "Packages" in the same directory as the Polly repository is, I was able to package the package by running `zip ../Packages/polly-git.xpi *` in the Polly repository directory.

**Comment by zakius** [comment]
Easiest way is using [web-ext](https://github.com/mozilla/web-ext) as it makes sure proper compression method is used and automatically excludes hidden directories, but technically yes, it's just a zip archive

Also, you can load unpacked extension temporarily (up to browser shutdown) on `about:debugging`
