### ISSUE TITLE
How to add polyfills?

### ISSUE THREAD

**Issue by KandiPanda** [zakius/Polly#8]
This may be a dumb question, but let's say that I want to add a polyfill, even if just to a local copy of the extension for my own testing purposes.

I get that I put the .js file in the polyfills folder and reference it in the manifest.

But for something like https://github.com/es-shims/RegExp.prototype.flags (one of many shims they provide, in this case one that adds missing RegExp flags such as dotAll), how do I know *which* .js file on that page I need to add? Or am I looking at this completely wrong, and I need to do something to the files there first to get the file that I need?

**Comment by zakius** [comment]
if it's not directly states in docs it's a trial and error thing, you generally want to find the file dedicated for direct browser use, often will be available in directory like `dist`, may also be published on some CDN

**Comment by zakius** [comment]
I just looked at the package you linked and it really seems that it needs to be built before linking it to the page. There are often few implementations available in the wild and it seems https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/flags#Polyfill would work just fine

**Comment by KandiPanda** [comment]
Tried adding the code in that little "Polyfill" code box as a `.js` file and pointed to it in the manifest, and while it seemed to add the option to the menu, I'm still getting `SyntaxError: invalid regular expression flag s` in console with it enabled, so it clearly isn't working for me. 

Not sure if I added it incorrectly (quite possible - did I need to add anything else to the .js file besides the code in the polyfill box?), or if I got the wrong thing from the page (slightly possible, though I doubt it), or if that particular implementation simply isn't capable of what I'm after?

**Comment by zakius** [comment]
I'll have to look at it, do you have some website that requires it to work so I can check it?

**Comment by KandiPanda** [comment]
Well, I first noticed it on https://store.steampowered.com/sale/tabletopfest (Which does work fine in the in-Steam browser, but fails to load anything below the event banner in Waterfox Classic), running into similar with pages such as https://store.steampowered.com/newshub/app/618950 (again fine in Steam, but I don't always feel like starting up Steam just to look at a page). 

Also for testing purposes, besides those pages, if you go to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/flags (the page you had linked) and add the `s` flag into either relevant location in the demo and click Run, it will still return `Error: invalid regular expression flag s` in the output box.

**Comment by zakius** [comment]
Okay, I misunderstood the issue at first: the property itself is supported, but new flags are not. Thanks for detailed explanation.

By the looks of it the `dotAll` flag is not supported and the shim you found only allows `flags` property to recognize it, but doesn't add support for the flag/property itself. Unfortunately I can't find polyfill that would add support of this.

Technically it would be possible to transform modern expressions to equivalent ones that are supported, there's even a Babel transformer doing that, but I'm not sure I'm willing to dive deep enough to get this working right now, sorry

**Comment by zakius** [comment]
Closing this as I see no viable way of supporting RegExp improvements and the title question is answered more or less
