### ISSUE TITLE
[1.3] GitHub scripts sometimes load before polyfills

### ISSUE THREAD

**Issue by magiruuvelvet** [zakius/Polly#9]
In v1.2 I had no issues using GitHub, but this version had problems in response handling. In 1.3 now scripts sometimes manage to load before the polyfills again. It's a hit and miss game. Most noticeable is the notification page when clicking on any button. Without polyfills loaded first the form POST action page is navigated to, rather than using AJAX.

**Comment by zakius** [comment]
have you checked the request modification method? I only left the `ContenteScript` for cases like imgur that don't need more invasive one

**Comment by magiruuvelvet** [comment]
Well I just checked the popup again and noticed a new entry "...request modification...". I enabled this for GitHub and now polyfills are definitely always loaded first. Sorry for not noticing that option earlier.

**Comment by zakius** [comment]
don't worry about that, I'm closing this issue then
